In [1]:
import pandas as pd
df=pd.read_csv("1745500125912-data.csv")
display(df)

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [4]:
df.columns

Index(['Actor', 'Film', 'Year', 'Genre', 'BoxOffice(INR Crore)', 'IMDb'], dtype='str')

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Actor                 12 non-null     str
 1   Film                  12 non-null     str
 2   Year                  12 non-null     int64
 3   Genre                 12 non-null     str
 4   BoxOffice(INR Crore)  12 non-null     int64
 5   IMDb                  12 non-null     float64
dtypes: float64(1), int64(2), str(3)
memory usage: 708.0 bytes

In [3]:
df.describe()

              Year  BoxOffice(INR Crore)       IMDb
count    12.000000             12.000000  12.000000
mean   2019.000000            545.666667   6.975000
std       2.215647            528.535942   0.981766
min    2016.000000            111.000000   5.600000
25%    2017.750000            249.750000   6.075000
50%    2018.500000            386.500000   7.000000
75%    2019.750000            570.000000   7.675000
max    2023.000000           2024.000000   8.400000

In [10]:
display(df["Actor"])
print(type(df["Actor"]))

0         Shah Rukh Khan
1            Salman Khan
2             Aamir Khan
3          Ranbir Kapoor
4          Ranveer Singh
5     Ayushmann Khurrana
6          Rajkummar Rao
7         Hrithik Roshan
8           Akshay Kumar
9          Kartik Aaryan
10          Varun Dhawan
11         Vicky Kaushal
Name: Actor, dtype: str

<class 'pandas.Series'>

In [11]:
df[["Actor","IMDb"]]

                 Actor  IMDb
0       Shah Rukh Khan   7.2
1          Salman Khan   6.0
2           Aamir Khan   8.4
3        Ranbir Kapoor   5.6
4        Ranveer Singh   7.0
5   Ayushmann Khurrana   8.3
6        Rajkummar Rao   7.5
7       Hrithik Roshan   6.5
8         Akshay Kumar   7.0
9        Kartik Aaryan   5.9
10        Varun Dhawan   6.1
11       Vicky Kaushal   8.2

In [ ]:
df.loc[1] #Access the data using row labels of row index

Actor                       Salman Khan
Film                    Tiger Zinda Hai
Year                               2017
Genre                            Action
BoxOffice(INR Crore)                565
IMDb                                6.0
Name: 1, dtype: object

In [ ]:
df.iloc[1] #Access the data using row index only

Actor                       Salman Khan
Film                    Tiger Zinda Hai
Year                               2017
Genre                            Action
BoxOffice(INR Crore)                565
IMDb                                6.0
Name: 1, dtype: object

In [ ]:
df.loc[8,"Genre"] #row index and column name

'Comedy'

In [ ]:
df.iloc[8,3] #row index and column index

'Comedy'

In [ ]:
df.loc[0:2,["Actor","IMDb","Film","Year"]] #last index is inclusive

            Actor  IMDb             Film  Year
0  Shah Rukh Khan   7.2          Pathaan  2023
1     Salman Khan   6.0  Tiger Zinda Hai  2017
2      Aamir Khan   8.4           Dangal  2016

In [ ]:
df.iloc[0:2,0:2] #last indexes of both rows and columns are exclusive

            Actor             Film
0  Shah Rukh Khan          Pathaan
1     Salman Khan  Tiger Zinda Hai

In [ ]:
df.at[0,"Actor"] #row index and column name, opitmized way of accessing a particular information
#designed for accessing a particular element only

'Shah Rukh Khan'

In [ ]:
df.iat[0,0] #row index and column index

'Shah Rukh Khan'

In [ ]:
df[df["IMDb"]>6] #filtering out those films whose IMDb rating is more than 6

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [ ]:
df[df["IMDb"]>7]["Actor"]
#getting only the names of the actors whose movie has IMDb rating of more than 6

0         Shah Rukh Khan
2             Aamir Khan
5     Ayushmann Khurrana
6          Rajkummar Rao
11         Vicky Kaushal
Name: Actor, dtype: str

In [ ]:
df[df["IMDb"]>6][["Actor","Year","Genre"]]
#getting only the names of the actors ,year and genre having more than 6 IMDb

                 Actor  Year            Genre
0       Shah Rukh Khan  2023           Action
2           Aamir Khan  2016        Biography
4        Ranveer Singh  2018       Historical
5   Ayushmann Khurrana  2018         Thriller
6        Rajkummar Rao  2018    Horror Comedy
7       Hrithik Roshan  2019           Action
8         Akshay Kumar  2019           Comedy
10        Varun Dhawan  2017  Romantic Comedy
11       Vicky Kaushal  2019           Action

In [ ]:
df[(df["IMDb"]>6) & (df["Year"]>2019)]["Film"] # and both conditions should be satisfied

0    Pathaan
Name: Film, dtype: str

In [33]:
df[(df["IMDb"]<6) & (df["Year"]>2019)]["Film"]

3           Brahmastra
9    Bhool Bhulaiyaa 2
Name: Film, dtype: str

In [34]:
df[(df["IMDb"]<6) | (df["Year"]>2019)]["Film"] # anyone condition should be satisfied

0              Pathaan
3           Brahmastra
9    Bhool Bhulaiyaa 2
Name: Film, dtype: str

In [36]:
df.query("Year>2019")

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9

In [37]:
df.query("Year>2018" and "IMDb>5")

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

df.query("25 < age <= 40")  Chained comparisons

7. Avoid using reserved keywords as column names
If you have a column named class, lambda, etc., you’ll need to use backticks:

df.query("`class` == 'Physics'")

8. Case-sensitive
Column names and string values are case-sensitive:

df.query("City == 'delhi'")  # ❌ if actual value is 'Delhi'

.query() returns a copy, not a view
The result is a new DataFrame. Changes won't affect the original unless reassigned:

filtered = df.query("age < 50")

4. You can use @ to reference Python variables
To pass external variables into .query():

age_limit = 30
df.query("age > @age_limit")

3. Use backticks for column names with spaces or special characters
If a column name has spaces, use backticks (`):

df.query("`first name` == 'Alice'")

2. String values must be in quotes
Use single or double quotes around strings in the expression:

df.query("name == 'Harry'")

If you have quotes inside quotes, mix them:

df.query('city == "Mumbai"')