In [4]:
import pandas as pd
df=pd.read_csv("data_cleaning_sample.csv")
print(df)

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [5]:
print(df.columns)

Index(['Name', 'Age', 'City', 'Gender', 'Email', 'Join Date'], dtype='str')

In [6]:
print("No of columns:",len(df.columns))
print("No of rows:",len(df))

No of columns: 6
No of rows: 9

In [7]:
print("Shape of the dataset:",df.shape)

Shape of the dataset: (9, 6)

In [ ]:
df.isnull() # True null value, False not a null value

    Name    Age   City  Gender  Email  Join Date
0  False  False  False   False  False      False
1  False   True  False   False  False      False
2  False  False  False   False  False      False
3  False   True  False   False  False      False
4  False  False  False   False  False      False
5   True  False  False   False  False       True
6  False  False  False   False  False      False
7  False  False  False   False  False      False
8  False   True  False   False  False      False

In [9]:
print("No of null values in each column of the dataset")
df.isnull().sum()

No of null values in each column of the dataset

Name         1
Age          3
City         0
Gender       0
Email        0
Join Date    1
dtype: int64

In [10]:
print("Percentage of null values in each column of the dataset")
print((df.isnull().sum()/len(df))*100)

Percentage of null values in each column of the dataset
Name         11.111111
Age          33.333333
City          0.000000
Gender        0.000000
Email         0.000000
Join Date    11.111111
dtype: float64

In [ ]:
df.dropna()       # Drop rows with *any* missing values
df.dropna(axis=0) # both are same

    Name   Age         City Gender              Email   Join Date
0  Alice  25.0     New York      F  alice@example.com  01-05-2021
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4  David  22.0       Mumbai      M  david@example.com  12-11-2019
6  Alice  25.0     New York      F  alice@example.com  01-05-2021
7  Alice  25.0     New York      F  alice@example.com  01-05-2021

In [ ]:
df.dropna(axis=1) # Drop columns with missing values

          City Gender              Email
0     New York      F  alice@example.com
1        Delhi      M    charlie@example
2  Los Angeles      M    bob@example.com
3        Delhi      M    charlie@example
4       Mumbai      M  david@example.com
5        Delhi      F     eve@domain.com
6     New York      F  alice@example.com
7     New York      F  alice@example.com
8        Delhi      M    charlie@example

In [ ]:
df.fillna(0) # Replace NaN with 0

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   0.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   0.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5        0  28.0        Delhi      F     eve@domain.com           0
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   0.0        Delhi      M    charlie@example  20-07-2021

In [20]:
ds=df["Age"].fillna(df["Age"].mean())
print(ds) # Replace Null values with mean in the age column

0    25.000000
1    25.833333
2    30.000000
3    25.833333
4    22.000000
5    28.000000
6    25.000000
7    25.000000
8    25.833333
Name: Age, dtype: float64

In [22]:
df.ffill()       # Forward fill fill the null value with the previous recent non null value

      Name        Age         City Gender              Email   Join Date
0    Alice  25.000000     New York      F  alice@example.com  01-05-2021
1  Charlie  25.833333        Delhi      M    charlie@example  20-07-2021
2      Bob  30.000000  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  25.833333        Delhi      M    charlie@example  20-07-2021
4    David  22.000000       Mumbai      M  david@example.com  12-11-2019
5    David  28.000000        Delhi      F     eve@domain.com  12-11-2019
6    Alice  25.000000     New York      F  alice@example.com  01-05-2021
7    Alice  25.000000     New York      F  alice@example.com  01-05-2021
8  Charlie  25.833333        Delhi      M    charlie@example  20-07-2021

In [23]:
df.bfill()      # Backward fill fill the null value with the next future non value

      Name        Age         City Gender              Email   Join Date
0    Alice  25.000000     New York      F  alice@example.com  01-05-2021
1  Charlie  25.833333        Delhi      M    charlie@example  20-07-2021
2      Bob  30.000000  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  25.833333        Delhi      M    charlie@example  20-07-2021
4    David  22.000000       Mumbai      M  david@example.com  12-11-2019
5    Alice  28.000000        Delhi      F     eve@domain.com  01-05-2021
6    Alice  25.000000     New York      F  alice@example.com  01-05-2021
7    Alice  25.000000     New York      F  alice@example.com  01-05-2021
8  Charlie  25.833333        Delhi      M    charlie@example  20-07-2021