In [1]:
import pandas as pd
df=pd.read_csv("data_cleaning_sample.csv")
display(df)

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [3]:
print(df.duplicated())

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7     True
8     True
dtype: bool

In [ ]:
clean_df=df.drop_duplicates() #To drop the duplicate rows
display(clean_df)

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN

In [10]:
print("The actual shape of the original dataset:")
print(df.shape)

The actual shape of the original dataset:
(9, 6)

In [ ]:
print("The actual shape of the cleaned dataset:")
print(clean_df.shape)

The actual shape of the cleaned dataset
(5, 6)

In [15]:
df.duplicated(subset=["Name","Age"])

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7     True
8     True
dtype: bool

In [22]:
df2=df.dropna()
display(df2)

    Name   Age         City Gender              Email   Join Date
0  Alice  25.0     New York      F  alice@example.com  01-05-2021
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4  David  22.0       Mumbai      M  david@example.com  12-11-2019
6  Alice  25.0     New York      F  alice@example.com  01-05-2021
7  Alice  25.0     New York      F  alice@example.com  01-05-2021

In [44]:
df2["Age"]=pd.to_numeric(df2["Age"], errors="coerce")

In [45]:
df2["Age Group"]=df2["Age"].apply(lambda x: "Adult" if x>=30 else "Minor")
display(df2)

    Name  Age         City Gender              Email   Join Date Age Group
0  Alice  NaN     New York      F  alice@example.com  01-05-2021     Minor
2    Bob  NaN  Los Angeles      M    bob@example.com  15-06-2020     Minor
4  David  NaN       Mumbai      M  david@example.com  12-11-2019     Minor
6  Alice  NaN     New York      F  alice@example.com  01-05-2021     Minor
7  Alice  NaN     New York      F  alice@example.com  01-05-2021     Minor