In [3]:
import pandas as pd
df=pd.read_csv("data_cleaning_sample.csv")
display(df)

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [4]:
df2=df.drop_duplicates()
display(df2)

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN

In [5]:
df2["Age Group"]=df2["Age"].apply(lambda x: "Adult" if x>=30 else "Minor")
display(df2)

      Name   Age         City Gender              Email   Join Date Age Group
0    Alice  25.0     New York      F  alice@example.com  01-05-2021     Minor
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021     Minor
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020     Adult
4    David  22.0       Mumbai      M  david@example.com  12-11-2019     Minor
5      NaN  28.0        Delhi      F     eve@domain.com         NaN     Minor

In [6]:
print(df2["Gender"].unique())

<StringArray>
['F', 'M']
Length: 2, dtype: str

In [7]:
gender_map={"M":"Male","F":"Female"}
df2["Gender"]=df2["Gender"].map(gender_map)
display(df2)

      Name   Age         City  Gender              Email   Join Date Age Group
0    Alice  25.0     New York  Female  alice@example.com  01-05-2021     Minor
1  Charlie   NaN        Delhi    Male    charlie@example  20-07-2021     Minor
2      Bob  30.0  Los Angeles    Male    bob@example.com  15-06-2020     Adult
4    David  22.0       Mumbai    Male  david@example.com  12-11-2019     Minor
5      NaN  28.0        Delhi  Female     eve@domain.com         NaN     Minor

In [8]:
df2["City"]=df2["City"].replace({"Delhi":"New Delhi","Mumbai":"Navi Mumbai"})
display(df2)

      Name   Age         City  Gender              Email   Join Date Age Group
0    Alice  25.0     New York  Female  alice@example.com  01-05-2021     Minor
1  Charlie   NaN    New Delhi    Male    charlie@example  20-07-2021     Minor
2      Bob  30.0  Los Angeles    Male    bob@example.com  15-06-2020     Adult
4    David  22.0  Navi Mumbai    Male  david@example.com  12-11-2019     Minor
5      NaN  28.0    New Delhi  Female     eve@domain.com         NaN     Minor