In [9]:
import pandas as pd
employees = pd.DataFrame({
    "EmpID": [1, 2, 3],
    "Name": ["Alice", "Bob", "Charlie"],
    "DeptID": [10, 20, 30]
})
 
departments = pd.DataFrame({
    "DeptID": [10, 20, 40],
    "DeptName": ["HR", "Engineering", "Marketing"]
})

In [10]:
pd.merge(employees,departments, on="DeptID") #Inner join based on DeptID

   EmpID   Name  DeptID     DeptName
0      1  Alice      10           HR
1      2    Bob      20  Engineering

In [11]:
pd.merge(employees, departments, on="DeptID", how="left")
# Keeps all employees, fills NaN where no match.

   EmpID     Name  DeptID     DeptName
0      1    Alice      10           HR
1      2      Bob      20  Engineering
2      3  Charlie      30          NaN

In [12]:
pd.merge(employees, departments, on="DeptID",how="right")
# Keeps all departments, even if no employee.

   EmpID   Name  DeptID     DeptName
0    1.0  Alice      10           HR
1    2.0    Bob      20  Engineering
2    NaN    NaN      40    Marketing

In [13]:
pd.merge(employees, departments, on="DeptID", how="outer")
# Includes all data, fills missing with NaN.

   EmpID     Name  DeptID     DeptName
0    1.0    Alice      10           HR
1    2.0      Bob      20  Engineering
2    3.0  Charlie      30          NaN
3    NaN      NaN      40    Marketing

In [23]:
df1=pd.DataFrame({"Name":["Alice","Bob"],"age":[13,14]})
df2=pd.DataFrame({"Name":["Charlie","David"],"age":[27,28]})

In [ ]:
pd.concat([df1,df2], axis=0) #Concatenates rows wise by default

      Name  age
0    Alice   13
1      Bob   14
0  Charlie   27
1    David   28

In [25]:
pd.concat([df1,df2], axis=1) #Concatenate column wise

    Name  age     Name  age
0  Alice   13  Charlie   27
1    Bob   14    David   28